name: jalaali
description: A flutter package to make working with solar date easier. You can convert dates to solar dates and manipulate those by using this package in your app.
version: 0.4.0
author: Moein Hosseini <mrdimaan@tuta.io>
homepage: https://github.com/mrdimaan/flutter_jalaali

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  test: ^1.5.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
